name: jWorldProtector
version: 0.1
author: Kodek
main: jcraft.wp.ProtectorPlugin

permissions:
  worldprotector.commands:
    default: op
  worldprotector.reload:
    default: op
  worldprotector.allow.lighter:
    default: op
  worldprotector.region:
    default: op

commands:
  worldprotector:
    aliases: [wp, worldpro]
    permission: worldprotector.commands
  region:
    aliases: [rg]
    permission: worldprotector.region